// Generated by CoffeeScript 1.3.3
(function() {
  var Calculator, calculator, chai, expect;

  chai = require("chai");

  Calculator = require("../calculator");

  calculator = new Calculator();

  expect = chai.expect;

  describe("Calculator", function() {
    return it("adds two numbers", function() {
      return expect(calculator.add("1,2")).to.equal(3);
    });
  });

}).call(this);
