// Generated by CoffeeScript 1.7.1
(function() {
  var Calculator, calculator, chai, expect;

  chai = require("chai");

  Calculator = require("../calculator");

  calculator = new Calculator();

  expect = chai.expect;

  describe("Calculator", function() {
    it("adds two numbers", function() {
      return expect(calculator.add("1,2")).to.equal(3);
    });
    it("handles a single number", function() {
      return expect(calculator.add("1")).to.equal(1);
    });
    it("returns 0 for an empty string", function() {
      return expect(calculator.add("")).to.equal(0);
    });
    it("adds multiple numbers", function() {
      return expect(calculator.add("1,2,3")).to.equal(6);
    });
    it("accepts new-line delimiters", function() {
      return expect(calculator.add("1\n2,3")).to.equal(6);
    });
    it("allows the specification of a delimiter", function() {
      return expect(calculator.add("//#\n1#2#3")).to.equal(6);
    });
    return it("throws an exception when a number is negative", function() {
      return expect(calculator.add("-1")).to["throw"](Calculator.inputError);
    });
  });

}).call(this);
