// Generated by CoffeeScript 1.3.3
(function() {
  var Calculator;

  Calculator = (function() {

    function Calculator() {}

    Calculator.prototype.add = function(string_of_numbers) {};

    return Calculator;

  })();

  module.exports = Calculator;

}).call(this);
