// Generated by CoffeeScript 1.7.1
(function() {
  var Calculator;

  Calculator = (function() {
    function Calculator() {}

    Calculator.inputError = new TypeError("negative numbers are not allowed");

    Calculator.prototype.add = function(numbers) {
      var delimiter, match, num, sum, _i, _len;
      if (numbers === "") {
        return 0;
      }
      match = numbers.match(/\/\/(.+?)\n(.*)/);
      if (match) {
        numbers = match[2];
        delimiter = match[1];
      } else {
        delimiter = ",";
      }
      numbers = numbers.split(RegExp("\\n|" + delimiter));
      sum = 0;
      for (_i = 0, _len = numbers.length; _i < _len; _i++) {
        num = numbers[_i];
        sum += parseInt(num);
        if (parseInt(num) < 0) {
          this.rejectNegatives();
        }
      }
      return sum;
    };

    Calculator.prototype.rejectNegatives = function() {
      throw this.inputError;
    };

    return Calculator;

  })();

  module.exports = Calculator;

}).call(this);
